#author : prajith.parammal@dxc.com
#Version : 1.0
#Auto Deploy linux VM from Template.
#Sample usage : ansible-playbook yml script, Run the script as below by populating required input in INVENTORY FILE
# $ ansible-playbook -i INVENTORY playbook/vm_deploy_template.yml

- name: Deploy linux VM from Template
  hosts: vcenter
  gather_facts: no
  connection: local
  tasks:
    - name: Creating VM from input template
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        validate_certs: no
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ item }}"
        from_template: yes
        template_src: "{{ template_file }}"
#        cluster: MainCluster
#        resource_pool: "/Resources"
#        vm_extra_config: 
#           folder: MyFolder
        esxi:
          datacenter: Lab
          hostname: "{{ esxi_hostname }}"
      with_inventory_hostnames:
        - NEW_VMS
